USE spring_blog_db;

insert into posts (title, body) values ('Phylliscum Lichen', 'Phylliscum Nyl.');
insert into posts (title, body) values ('Silver Palm', 'Coccothrinax Sarg.');
insert into posts (title, body) values ('Plummer''s Mariposa Lily', 'Calochortus plummerae Greene');
insert into posts (title, body) values ('Brachythecium Moss', 'Brachythecium collinum (Schleich. ex Müll. Hal.) Schimp.');
insert into posts (title, body) values ('Church''s Wildrye', 'Elymus churchii J.J.N. Campb.');
insert into posts (title, body) values ('Oahu Rollandia', 'Cyanea humboldtiana (Gaudich.) Lammers, Givnish & Sytsma');
insert into posts (title, body) values ('Cracked Lichen', 'Acarospora albomarginata (Herre) Salisb.');
insert into posts (title, body) values ('Sweet Birch', 'Betula lenta L.');
insert into posts (title, body) values ('Island Glorybush', 'Trembleya phlogiformis DC.');
insert into posts (title, body) values ('Asiatic Mangrove', 'Rhizophora mucronata Lam.');
insert into posts (title, body) values ('Mountain Arnica', 'Arnica montana L.');
insert into posts (title, body) values ('Subarctic Ladyfern', 'Athyrium filix-femina (L.) Roth ssp. angustum (Willd.) R.T. Clausen');
insert into posts (title, body) values ('Agracejo Rastrero', 'Evolvulus nummularius (L.) L.');
insert into posts (title, body) values ('Bornean Ironwood', 'Eusideroxylon lauriflora (Blanco) J. Schultze-Motel');
insert into posts (title, body) values ('Japanese Azalea', 'Rhododendron japonicum (A. Gray) Sur.');
insert into posts (title, body) values ('Sierra Milkwort', 'Polygala cornuta Kellogg var. fishiae (Parry) Jeps.');
insert into posts (title, body) values ('Salmonberry', 'Rubus spectabilis Pursh var. spectabilis');
insert into posts (title, body) values ('Greenscale Willow', 'Salix chlorolepis Fernald');
insert into posts (title, body) values ('Prostrate Starwort', 'Stellaria prostrata Baldw.');
insert into posts (title, body) values ('Lakeshore Sedge', 'Carex lenticularis Michx. var. impressa (L.H. Bailey) L.A. Standl.');
insert into posts (title, body) values ('Nye County Fishhook Cactus', 'Sclerocactus nyensis F. Hochstätter');
insert into posts (title, body) values ('Lady Tulip', 'Tulipa clusiana DC.');
insert into posts (title, body) values ('Bush Oak', 'Quercus ×bushii Sarg.');
insert into posts (title, body) values ('Fuzzystem Phyllostegia', 'Phyllostegia wawrana Sherff');
insert into posts (title, body) values ('Green Adder''s-mouth Orchid', 'Malaxis unifolia Michx.');
insert into posts (title, body) values ('Gloria De La Manana', 'Ipomoea carnea Jacq. ssp. fistulosa (Mart. ex Choisy) D. Austin');
insert into posts (title, body) values ('Eranthis', 'Eranthis Salisb.');
insert into posts (title, body) values ('Britton''s Maiden Fern', 'Thelypteris brittonae (Slosson ex Maxon) Alain');
insert into posts (title, body) values ('Smooth Beggartick', 'Bidens laevis (L.) Britton, Sterns & Poggenb.');
insert into posts (title, body) values ('Chinese-plumbago', 'Ceratostigma willmottianum Stapf');
insert into posts (title, body) values ('French Broom', 'Genista monspessulana (L.) L.A.S. Johnson');
insert into posts (title, body) values ('Gypsyflower', 'Cynoglossum officinale L.');
insert into posts (title, body) values ('Larsen''s Ironweed', 'Vernonia larseniae B.L. King & S.B. Jones');
insert into posts (title, body) values ('Hairy Bugseed', 'Corispermum villosum Rydb.');
insert into posts (title, body) values ('Touret''s Scleropodium Moss', 'Scleropodium touretii (Brid.) L.F. Koch var. colpophyllum (Sull.) E. Lawton ex H.A. Crum');
insert into posts (title, body) values ('Spreading Chinchweed', 'Pectis prostrata Cav.');
insert into posts (title, body) values ('Vancouver Thistle', 'Cirsium ×vancouverense J.W. Moore & Frankton');
insert into posts (title, body) values ('New Mexico Phacelia', 'Phacelia neomexicana Thurb. ex Torr.');
insert into posts (title, body) values ('Tree Limonium', 'Limonium arborescens (Brouss.) Kuntze');
insert into posts (title, body) values ('Minthorn''s Milkvetch', 'Astragalus minthorniae (Rydb.) Jeps. var. villosus Barneby');
insert into posts (title, body) values ('Muttongrass', 'Poa fendleriana (Steud.) Vasey ssp. fendleriana');
insert into posts (title, body) values ('Goldenfleece', 'Ericameria arborescens (A. Gray) Greene');
insert into posts (title, body) values ('Mojave Panicgrass', 'Panicum mohavense J. Reeder');
insert into posts (title, body) values ('Intermountain Clover', 'Trifolium andinum Nutt. var. podocephalum Barneby');
insert into posts (title, body) values ('Dryostichum', '×Dryostichum singulare W.H. Wagner');
insert into posts (title, body) values ('Cayratia', 'Cayratia Juss.');
insert into posts (title, body) values ('Common Gorse', 'Ulex europaeus L.');
insert into posts (title, body) values ('California Fetid Adderstongue', 'Scoliopus bigelovii Torr.');
insert into posts (title, body) values ('Compact Prairie Clover', 'Dalea compacta Spreng. var. pubescens (A. Gray) Barneby');
insert into posts (title, body) values ('Climbing Cactus', 'Epiphyllum phyllanthus (L.) Haw. [excluded]');
insert into posts (title, body) values ('Shaggystem Cyrtandra', 'Cyrtandra oenobarba H. Mann');
insert into posts (title, body) values ('Red Mountain Stonecrop', 'Sedum eastwoodiae (Britton) A. Berger');
insert into posts (title, body) values ('Sclerophora Lichen', 'Sclerophora nivea (Hoffm.) Tibell');
insert into posts (title, body) values ('Aloe', 'Aloe L.');
insert into posts (title, body) values ('Parry''s Townsend Daisy', 'Townsendia parryi D.C. Eaton');
insert into posts (title, body) values ('Alkali Desertparsley', 'Lomatium caruifolium (Hook. & Arn.) J.M. Coult. & Rose var. caruifolium');
insert into posts (title, body) values ('Ricegrass', 'Oryzopsis holciformis (M. Bieb.) Hack.');
insert into posts (title, body) values ('Panicum', 'Panicum paniculatum Kuntze');
insert into posts (title, body) values ('Snapdragon Penstemon', 'Keckiella antirrhinoides (Benth.) Straw');
insert into posts (title, body) values ('Campylopus Moss', 'Campylopus subulatus Schimp.');
insert into posts (title, body) values ('Big-spore Quillwort', 'Isoetes macrospora Durieu');
insert into posts (title, body) values ('Syngonium', 'Syngonium Schott');
insert into posts (title, body) values ('Juniper Skin Lichen', 'Leptogium juniperinum Tuck.');
insert into posts (title, body) values ('Navajo Bladderpod', 'Lesquerella navajoensis O''Kane');
insert into posts (title, body) values ('Pohil''s Milkvetch', 'Astragalus lentiginosus Douglas ex Hook. var. pohlii S.L. Welsh & Barneby');
insert into posts (title, body) values ('Toothed Five Eyes', 'Chamaesaracha crenata Rydb.');
insert into posts (title, body) values ('Narrowleaf Gumweed', 'Grindelia lanceolata Nutt. var. lanceolata');
insert into posts (title, body) values ('Barbados Cherry', 'Malpighia emarginata Sessé & Moc. ex DC.');
insert into posts (title, body) values ('Golden Hedgehyssop', 'Gratiola aurea Pursh');
insert into posts (title, body) values ('Pungent Oak', 'Quercus pungens Liebm.');
insert into posts (title, body) values ('Greenland Fescue', 'Festuca groenlandica (Schol.) Fred.');
insert into posts (title, body) values ('Faurie''s Panicgrass', 'Panicum fauriei Hitchc. var. latius (H. St. John) Davidse');
insert into posts (title, body) values ('Torrid Rim Lichen', 'Lecanora torrida Vain.');
insert into posts (title, body) values ('Nakedstem Carpetweed', 'Mollugo nudicaulis Lam. var. nudicaulis');
insert into posts (title, body) values ('Dot Lichen', 'Arthonia mediella Nyl.');
insert into posts (title, body) values ('Oldwoman', 'Artemisia stelleriana Besser');
insert into posts (title, body) values ('Fivewing Spiderling', 'Boerhavia intermedia M.E. Jones');
insert into posts (title, body) values ('Smooth-seed Pygmyweed', 'Crassula solieri (Gay) F. Meigen');
insert into posts (title, body) values ('Bush''s Blackberry', 'Rubus bushii L.H. Bailey');
insert into posts (title, body) values ('Plumed Spikemoss', 'Selaginella plumosa (L.) C. Presl');
insert into posts (title, body) values ('White Mountain False Pennyroyal', 'Hedeoma pulcherrima Wooton & Standl.');
insert into posts (title, body) values ('Graphina Lichen', 'Graphina columbina (Tuck.) M. Wirth & Hale');
insert into posts (title, body) values ('Hammock Velvetseed', 'Guettarda elliptica Sw.');
insert into posts (title, body) values ('Roccellina Lichen', 'Roccellina conformis Tehler');
insert into posts (title, body) values ('Big Horseshoe Lake Dewberry', 'Rubus stipulatus L.H. Bailey');
insert into posts (title, body) values ('Dwarf Clover', 'Trifolium nanum Torr.');
insert into posts (title, body) values ('Somerset Hair Grass', 'Koeleria vallesiana (Honck.) Gaudin');
insert into posts (title, body) values ('Western Snow Lichen', 'Stereocaulon dactylophyllum Flörke var. occidentale (H. Magn.) Lamb');
insert into posts (title, body) values ('Cottonheads', 'Nemacaulis denudata Nutt. var. denudata');
insert into posts (title, body) values ('Hana Clermontia', 'Clermontia samuelii Forbes ssp. hanaensis (H. St. John) Lammers');
insert into posts (title, body) values ('Wyoming Xanthoparmelia Lichen', 'Xanthoparmelia wyomingica (Gyel.) Hale');
insert into posts (title, body) values ('Mountain Carpet Clover', 'Trifolium monanthum A. Gray ssp. grantianum (A. Heller) J.M. Gillett');
insert into posts (title, body) values ('Allegheny Mountain Goldenbanner', 'Thermopsis mollis (Michx.) M.A. Curtis ex A. Gray');
insert into posts (title, body) values ('Oncosiphon', 'Oncosiphon Källersjö');
insert into posts (title, body) values ('Texas Pinkroot', 'Spigelia texana (Torr. & A. Gray) A. DC.');
insert into posts (title, body) values ('Nevada Pea', 'Lathyrus lanszwertii Kellogg var. aridus (Piper) Jeps.');
insert into posts (title, body) values ('Beach Starwort', 'Stellaria littoralis Torr.');
insert into posts (title, body) values ('Arizona Beard Lichen', 'Usnea arizonica Mot.');
insert into posts (title, body) values ('Pigweed', 'Amaranthus ×texensis Henrickson');
insert into posts (title, body) values ('Hybrid Oak', 'Quercus ×atlantica Ashe (pro sp.)');
insert into posts (title, body) values ('Velvet Lupine', 'Lupinus leucophyllus Douglas ex Lindl. ssp. erectus (L.F. Hend.) Harmon');
